# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnLERPVMMBxVhSLFI09hNYhTxCp9Vval
"""



import streamlit as st
import pandas as pd

st.title("🦶 Diabetic Foot Pressure Grading (3-Sensor Dataset)")


uploaded_file = st.file_uploader("PRESSURE OUTPUT", type=["xlsx"])

def grade_pressure(value):
    if value < 30:
        return "Grade 1 (Low)"
    elif value < 70:
        return "Grade 2 (Moderate)"
    else:
        return "Grade 3 (High)"

def process_data(df):
    for sensor in ["Sensor1", "Sensor2", "Sensor3"]:
        df[f"{sensor}_Grade"] = df[sensor].apply(grade_pressure)

    df["Mean_Pressure"] = df[["Sensor1", "Sensor2", "Sensor3"]].mean(axis=1)
    df["Overall_Grade"] = df["Mean_Pressure"].apply(grade_pressure)
    return df

if uploaded_file is not None:
    try:
        df = pd.read_excel(uploaded_file)
        st.success("✅ File uploaded successfully!")
        st.write("📊 Raw Data:", df.head())

        if all(sensor in df.columns for sensor in ["Sensor1", "Sensor2", "Sensor3"]):
            processed_df = process_data(df)
            st.subheader("🩺 Grading Result:")
            st.dataframe(processed_df)

            # Download processed file
            output_file = "graded_output.xlsx"
            processed_df.to_excel(output_file, index=False)
            with open(output_file, "rb") as f:
                st.download_button("📥 Download Graded Excel", data=f, file_name="graded_output.xlsx")

        else:
            st.error("❌ Columns 'Sensor1', 'Sensor2', and 'Sensor3' are required.")

    except Exception as e:
        st.error(f"⚠️ Error: {e}")